### PR TITLE
Apply formatting changes from code review

### PR DESCRIPTION
**Pull request by SusiJo**
Many thanks to contributing to nf-core/bamtofastq!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, add test data to `testdata/` 
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`). 
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/qbic-pipelines/bamtofastq/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by SusiJo** [comment]
Linting is expected to fail, because the `Contributing.md` differs from the pipeline template. However, the pipeline template of `nf-core/tools` version 2.8 is outdated as it lists a `Dockerfile` which should not be there anymore.

**Review by JoseEspinosa — APPROVED** [review]
Awesome! :rocket:

**Comment by JoseEspinosa** [comment]
> Linting is expected to fail, because the `Contributing.md` differs from the pipeline template. However, the pipeline template of `nf-core/tools` version 2.8 is outdated as it lists a `Dockerfile` which should not be there anymore.

Adding this to the `.nf-core.yml` should do the trick:
```
lint:
  files_unchanged:
    - ..github/CONTRIBUTING.md
```
See [here](https://nf-co.re/tools/#linting-config)

**Comment by SusiJo** [comment]
Thanks @JoseEspinosa!

**Pull request merged**
