### PR TITLE
tweak usage.md

### PR DESCRIPTION
**Pull request by allaway**
To (partially?) address #67, minor adjustment to docs. 😄 

I believe these are the only two relevant checkboxes for this PR: 
- [X] This comment contains a description of changes (with reason).
- [X] Usage Documentation in `docs/usage.md` is updated.

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
Hey! Thanks for fixing the docs. In fact, looks like the file_type is also mandatory : https://github.com/nf-core/bamtofastq/blob/c70f49b20c83c72a0e6198e4b13edb5e2fb14725/assets/schema_input.json#L37 . Could you add that?

**Comment by allaway** [comment]
> Hey! Thanks for fixing the docs. In fact, looks like the file_type is also mandatory :
> 
> https://github.com/nf-core/bamtofastq/blob/c70f49b20c83c72a0e6198e4b13edb5e2fb14725/assets/schema_input.json#L37
> . Could you add that?

Ah, ok, that makes sense as to why the docs originally said three columns are required. I'll fix this!

**Comment by allaway** [comment]
@FriederikeHanssen - let me know if you would like to see any other changes! I also made some changes to make the column names more consistent in the docs.

**Comment by FriederikeHanssen** [comment]
@nf-core-bot fix linting

**Review by FriederikeHanssen — APPROVED** [review]
Wonderful, thanks a lot 😊 just waiting for the bot to fix linting and then can merge

**Pull request merged**
